version: 0.2
phases:
  install:
    commands:
      - npm install
      - export BUCKET=codepipeline-us-east-1-875168509671
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml --s3-prefix $(date +%Y-%m-%d)
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml
