version: 0.2
phases:
  install:
    commands:
      - cd hello_world
      - npm install
      - cd ..
      - export BUCKET=codepipeline-us-east-1-875168509671
      - aws cloudformation package --template-file template.yaml --output-template-file outputtemplate.yaml --s3-bucket $BUCKET --s3-prefix lambda-sam-pipeline/compiledCloudFrontTemplates --debug
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml
